# Generated by Django 5.2.15 on 2026-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Send Log', 'verbose_name_plural': 'Send Logs'},
        ),
        migrations.AlterField(
            model_name='sendlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
