# Generated by Django 5.2.15 on 2026-06-25 16:30

import django.contrib.auth.validators
import django.utils.timezone
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gmail_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted Gmail OAuth2 access token.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gmail_connected',
            field=models.BooleanField(default=False, help_text='True when a valid Gmail OAuth connection exists.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gmail_refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted Gmail OAuth2 refresh token.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gmail_token_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiry datetime of the current access token.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Gmail address used for sending. Set after OAuth.', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Display name shown in outgoing emails.', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
