# Generated by Django 5.2.15 on 2026-06-26 09:06

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted Gemini API Key provided by the user.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_text',
            field=models.TextField(blank=True, help_text="Extracted text from the user's resume PDF."),
        ),
    ]
