# Generated by Django 5.2.15 on 2026-06-27 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_gemini_api_key_userprofile_resume_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Frontend Developer, Data Scientist', max_length=200)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('parsed_text', models.TextField(blank=True, help_text='Text extracted from the resume PDF for AI matching')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Resume',
                'verbose_name_plural': 'User Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
