# Generated by Django 5.2.15 on 2026-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='True if the user has completed the onboarding flow.'),
        ),
    ]
