# Generated by Django 5.2.15 on 2026-07-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_is_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted structured resume data (summary, skills, experience, education, etc.)'),
        ),
    ]
