# Generated by Django 5.2.15 on 2026-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userresume_structured_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/'),
        ),
    ]
