# Generated by Django 5.2.15 on 2026-07-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userresume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-3.5-flash', help_text='The Gemini model to use for AI tasks (e.g. gemini-3.5-flash, gemini-1.5-flash, gemini-1.5-pro, etc.).', max_length=50),
        ),
    ]
