# Generated by Django 5.2.15 on 2026-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_update_gemini_model_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-3.5-flash', help_text='Gemini model used for AI tasks. Current options: gemini-3.5-flash (recommended), gemini-2.5-flash, gemini-2.5-pro, gemini-2.0-flash, gemini-1.5-flash, gemini-1.5-pro.', max_length=50),
        ),
    ]
