# Generated by Django 5.2.15 on 2026-07-16 09:12

from django.db import migrations, models


def migrate_gemini_models(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(gemini_model__in=['gemini-1.5-flash', 'gemini-1.5-pro']).update(gemini_model='gemini-2.5-flash')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_aiusagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-2.5-flash', help_text='Gemini model used for AI tasks. Current options: gemini-2.5-flash (recommended), gemini-2.5-pro, gemini-2.0-flash.', max_length=50),
        ),
        migrations.RunPython(migrate_gemini_models, reverse_code=migrations.RunPython.noop),
    ]
