# Generated by Django 5.2.15 on 2026-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipientlist',
            options={'ordering': ['created_at'], 'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Full row from the spreadsheet after column mapping applied.'),
        ),
    ]
