# Generated by Django 5.2.15 on 2026-06-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_alter_recipientlist_options_alter_recipientlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientlist',
            name='is_opened',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='recipientlist',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipientlist',
            name='opened_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
