# Generated by Django 5.2.15 on 2026-07-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_recipientlist_is_opened_recipientlist_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientlist',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
