# Generated by Django 5.2.15 on 2026-07-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_recipientlist_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientlist',
            name='linkedin_url',
        ),
    ]
