# Generated by Django 5.2.15 on 2026-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_sheet_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Maps spreadsheet column names to template variables. e.g. {"B": "recipient_name"}'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='send_delay_seconds',
            field=models.FloatField(default=1.5, help_text='Delay in seconds between individual email sends to avoid Gmail rate limits.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject_template',
            field=models.CharField(help_text='Email subject, may include {{ variable_name }} placeholders.', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='available_variables',
            field=models.JSONField(default=list, help_text='List of variable names extracted from html_body.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_body',
            field=models.TextField(help_text='HTML content with {{ variable_name }} placeholders.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
