# Generated by Django 5.2.15 on 2026-06-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userresume'),
        ('campaigns', '0002_alter_campaign_options_alter_emailtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='resume',
            field=models.ForeignKey(blank=True, help_text='The resume selected for this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='accounts.userresume'),
        ),
    ]
