# Generated by Django 5.2.15 on 2026-06-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='opened_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
