# Generated by Django 5.2.15 on 2026-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_opened_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='open_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Inject a hidden pixel to track email opens. Turn off to maximize deliverability.'),
        ),
    ]
