# Generated by Django 5.2.15 on 2026-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_open_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Default email subject template.', max_length=250),
        ),
    ]
