# Generated by Django 5.2.15 on 2026-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_emailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='subject_template',
            field=models.CharField(blank=True, default='', help_text='Email subject, may include {{ variable_name }} placeholders.', max_length=500),
        ),
    ]
