# Generated by Django 5.2.15 on 2026-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_subject_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='plain_text_mode',
            field=models.BooleanField(default=False, help_text='Send as plain-text only (no HTML). Maximises inbox placement for cold job-application outreach. When enabled, HTML is stripped and no tracking pixel is injected regardless of open_tracking_enabled.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='open_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Inject a hidden pixel to track email opens. Disabled by default for better deliverability.'),
        ),
    ]
