# Generated by Django 5.2.15 on 2026-07-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_add_plain_text_mode_fix_tracking_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_connection_template',
            field=models.CharField(blank=True, default='', help_text='LinkedIn connection message template (max 300 characters recommended).', max_length=500),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('linkedin_inmail', 'LinkedIn InMail'), ('linkedin_connection', 'LinkedIn Connection Request')], default='email', max_length=25),
        ),
    ]
