# Generated by Django 5.2.15 on 2026-07-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_remove_campaign_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
