# Generated by Django 5.2.15 on 2026-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedcontact',
            options={'ordering': ['created_at'], 'verbose_name': 'Scraped Contact', 'verbose_name_plural': 'Scraped Contacts'},
        ),
        migrations.AlterModelOptions(
            name='scrapejob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scrape Job', 'verbose_name_plural': 'Scrape Jobs'},
        ),
        migrations.AlterField(
            model_name='scrapedcontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
