# Generated by Django 5.2.15 on 2026-06-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_alter_emailtemplate_options_and_more'),
        ('scraper', '0002_alter_scrapedcontact_options_alter_scrapejob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontact',
            name='custom_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_jobs', to='campaigns.campaign'),
        ),
    ]
