# Generated by Django 5.2.15 on 2026-06-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapedcontact_custom_variables_scrapejob_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='use_ai_matching',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('web', 'Web Search (ATS)'), ('glassdoor', 'Glassdoor'), ('wellfound', 'Wellfound'), ('foundit', 'Foundit (Monster)'), ('dice', 'Dice')], max_length=20),
        ),
    ]
