# Generated by Django 5.2.15 on 2026-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_scrapedcontact_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('web', 'Web Search (DuckDuckGo)'), ('glassdoor', 'Glassdoor'), ('wellfound', 'Wellfound'), ('foundit', 'Foundit (Monster)'), ('dice', 'Dice')], max_length=20),
        ),
    ]
