# Generated by Django 5.2.15 on 2026-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_scrapejob_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcontact',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='scrapedcontact',
            name='source_url',
            field=models.URLField(blank=True, max_length=10000),
        ),
    ]
