# Generated by Django 5.2.15 on 2026-07-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_scrapedcontact_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedcontact',
            options={'ordering': ['id'], 'verbose_name': 'Scraped Contact', 'verbose_name_plural': 'Scraped Contacts'},
        ),
    ]
