# Generated by Django 5.2.15 on 2026-07-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_companyenrichment_companyemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontact',
            name='posted_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
