# Generated by Django 5.2.15 on 2026-07-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_scrapedcontact_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcontact',
            name='posted_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
