# Generated by Django 5.2.15 on 2026-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_alter_scrapedcontact_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontact',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='scrapedcontact',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
