# Generated by Django 5.2.15 on 2026-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_scrapedcontact_location_scrapedcontact_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='company_size',
            field=models.CharField(default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='freshness',
            field=models.CharField(default='any', max_length=20),
        ),
    ]
