# Generated by Django 5.2.15 on 2026-07-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_scrapejob_company_size_scrapejob_freshness'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='profile_insights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='role_description',
            field=models.TextField(blank=True),
        ),
    ]
