# Generated by Django 5.2.15 on 2026-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_companyemployee_profile_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyenrichment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
