# Generated by Django 5.2.15 on 2026-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_profileresearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileresearch',
            name='headline',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profileresearch',
            name='total_experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
